42EASY/PongPongPingPong

backend/transcendence/games/distributed_lock.py, backend/transcendence/games/game_consumer.py, backend/transcendence/games/game_queue_consumer.py, backend/transcendence/games/game_room_consumer.py
- https://github.com/42EASY/PongPongPingPong/issues/138
- 게임 큐를 redis에 저장해두고 있는데, 접근 시에 간헐적으로 race condition 문제가 발생
- redis의 기능 중 하나인 SETNX를 사용한 분산 락을 구현하여 문제 해결
=> fix: 분산 락으로 동시성 문제 해결

backend/transcendence/games/game_consumer.py, backend/transcendence/games/game_queue_consumer.py, backend/transcendence/games/game_room_consumer.py
경로를 지정하여 import할 Class를 찾을 수 있도록 했습니다
=> fix: 경로 지정

backend/transcendence/members/modelSerializer.py, backend/transcendence/members/models.py, backend/transcendence/members/views.py, backend/transcendence/security/auth_views.py, backend/transcendence/transcendence/settings.py
- https://github.com/42EASY/PongPongPingPong/issues/145
- 닉네임 유효성 검사 추가(길이, 허용 문자, 중복)
- 가입시 닉네임 랜덤한 값으로 변경
- 가입시 기본 프로필 사진 설정
=> fix: 멤버 첫 로그인 로직 변경

backend/transcendence/games/game_queue_consumer.py, backend/transcendence/games/game_room_consumer.py, backend/transcendence/games/test_game_consumer.py, backend/transcendence/games/test_game_queue_consumer.py, backend/transcendence/games/test_game_room_consumer.py
- https://github.com/42EASY/PongPongPingPong/issues/148
- websocket에서 action과 함께 같이 들어오는 파라미터 중에 사용하지 않는 파라미터들 삭제 처리
=> fix: 사용하지 않는 param들 정리

backend/transcendence/games/game_consumer.py, backend/transcendence/games/game_queue_consumer.py, backend/transcendence/games/game_room_consumer.py, backend/transcendence/games/test_game_queue_consumer.py
- https://github.com/42EASY/PongPongPingPong/issues/132
game websocket 부분에서 세세한 부분들 수정 및 테스트 완료
- model 접근 부분 try, except 문 사용하여 감싸줌
- redis에 들어가는 접두사들 (normal_, tournament_) 모두 변수로 관리
- action 시에 들어오는 파라미터들 유효성 검증
- tournament_id와 room_id 혼용한 부분 room_id로 통일
=> fix: game websocket 세세한 부분 수정

backend/Dockerfile, backend/docker_entrypoint.sh, backend/transcendence/run_daphne.py, docker-compose.yml
- https://github.com/42EASY/PongPongPingPong/issues/161
- backend 볼륨 설정
- 스크립트를 사용하여 코드 변경 감지 후 서버 재시작할 수 있도록 변경
=> feat: restart daphne

backend/transcendence/chat/consumers.py, backend/transcendence/notify/admin.py, backend/transcendence/notify/apps.py, backend/transcendence/notify/consumer.py, backend/transcendence/notify/models.py, backend/transcendence/notify/tests.py, backend/transcendence/notify/views.py, backend/transcendence/transcendence/routing.py
- https://github.com/42EASY/PongPongPingPong/issues/152
- 알림 Consumer와 채팅 Consumer를 분리하였습니다
- 채팅 컨슈머는 알림 컨슈머를 상속 받습니다
- 프론트와 기능을 붙이면서 부족한 부분을 더 추가할 예정입니다.
=> refactor: 채팅 기능과 알림 기능 분리

frontend/src/components/Chat/ChatRoom/ChatContents.js, frontend/src/components/Chat/ChatRoom/Title.js, frontend/src/pages/Chat.js, frontend/src/pages/ChatRoom.js, frontend/src/pages/Friends.js, frontend/src/pages/Nav.js, frontend/src/state/State.js, frontend/src/styles/sidebar.css
- https://github.com/42EASY/PongPongPingPong/issues/160
* getMyInfo() 함수 만들고 chatroom에 적용했습니다
return { user_id, nickname, image_url }
* nav에서 친구 검색할 때 이벤트가 중첩되어 여러번 getUserInfo(id)를 호출하던 부분 수정했습니다.
* chat과 friends의 타이틀을 상단에 고정시키고 스크롤 구현했습니다.
=> fix: state 추가, sidebar scroll 적용

backend/docker_entrypoint.sh, backend/transcendence/chat/consumers.py, backend/transcendence/notify/consumer.py
- https://github.com/42EASY/PongPongPingPong/issues/164
- redis 호스트 변경
- json.dump encoding 하는 메서드 추가
- loaddata 경로 수정
=> fix: ChatConsumer 수정

frontend/src/components/Chat/ChatRoom/ChatContents.js, frontend/src/styles/sidebar.css
=> fix: chatting input

Makefile, backend/transcendence/security/auth_views.py, frontend/src/components/Chat/ChatList.js, frontend/src/components/Login/Redirect.js, frontend/src/pages/Chat.js, frontend/src/pages/ChatRoom.js, frontend/src/state/State.js, frontend/src/styles/sidebar.css
- 새로운 채팅이 올 때마다 스크롤이 아래로 내려가도록 설정했습니다
- 채팅방 받아오는 로직을 변경했습니다
=> fix: 채팅방 오류 수정

frontend/src/components/Chat/Bot.js, frontend/src/components/Chat/ChatRoom/BotContent.js, frontend/src/components/Chat/ChatRoom/ChatContent.js, frontend/src/components/Modal/GameResultTable.js, frontend/src/components/Modal/TournamentTable.js, frontend/src/components/Nav/JoinQueue.js, frontend/src/pages/BotRoom.js, frontend/src/pages/Chat.js, frontend/src/pages/ChatRoom.js, frontend/src/styles/modal.css, frontend/src/styles/sidebar.css
- https://github.com/42EASY/PongPongPingPong/issues/172
chat의 bot에 필요한 채팅방 게임결과 컴포넌트를 구현했습니다.
게임방에 필요한 대진표 컴포넌트도 추가했습니다.
modal에서 컴포넌트 추가할 때 :
modal("gameResultTable", data);
-> GameResultTable(data);
modal("tournamentTable", data);
-> TournamentTable(data.player_info);
-> data.mode = "SEMI_FINAL" | "FINAL";
현재 width: 400px; 로 되어있는데 변경할 때 
modal.css - .tableWrapper - width 값 수정하면 됩니다!
=> fix: bot content 추가

backend/transcendence/chat/consumers.py
- https://github.com/42EASY/PongPongPingPong/issues/164
- 차단 유저에게 메세지를 받지 않도록 수정하였습니다.
- 차단을 한 경우에는 메세지를 보낼 수도, 받을 수도 없게 처리하였습니다.
- 차단을 풀면 메세지가 다시 보이게 됩니다.
=> feat: ChatConsumer 차단 유저 관련 기능 추가

backend/transcendence/games/game_queue_consumer.py, backend/transcendence/games/test_game_queue_consumer.py
- https://github.com/42EASY/PongPongPingPong/issues/181
- 게임 큐 소켓에서 cancel하는 action을 구현 
- 테스트코드 작성 및 테스트 완료
=> feat: 게임 큐 cancel action 구현

backend/transcendence/games/game_room_consumer.py, backend/transcendence/games/test_game_room_consumer.py
- https://github.com/42EASY/PongPongPingPong/issues/166
- 게임 방에 유저가 입장할 때 마다 플레이어 정보를 반환하도록 수정
=> fix: 게임방에 유저 입장 시 플레이어 정보 반환

frontend/src/components/Chat/Chat.js, frontend/src/components/Main/UserApi.js, frontend/src/components/Modal/ModalsInfo.js, frontend/src/pages/Chat.js, frontend/src/pages/ChatRoom.js, frontend/src/state/ChatSocketManager.js, frontend/src/state/ChatUserState.js
- https://github.com/42EASY/PongPongPingPong/issues/189
- 채팅 중인 유저 상태 관리를 위한 `chatUserState` 추가
- `chatUserState`를 사용해 오프라인 & 차단 유저 관련 예외 처리
- 오프라인 & 차단 유저 경고 모달 추가
- 채팅 소켓과 알림 소켓 분리
=> feat: 유저 상태 관리 기능 구현

backend/transcendence/games/game_consumer.py, backend/transcendence/games/test_game_consumer.py
- https://github.com/42EASY/PongPongPingPong/issues/191
게임 방 소켓에서 자잘한 오류 수정
- game_over시에 broadcast 하는 부분 문단 오류 수정 및 redis 삭제 로직 추가
- 게임 도중 disconnect시 게임 결과 정보까지 다른 유저에게 send 되도록 수정
=> fix: 게임 방 소켓 자잘한 오류 수정

frontend/src/Router.js, frontend/src/components/Friends/Options.js, frontend/src/components/Nav/FastGameStart.js, frontend/src/components/Nav/InviteQueue.js, frontend/src/components/Nav/JoinQueue.js, frontend/src/components/Nav/NavApi.js, frontend/src/pages/Main.js, frontend/src/pages/Nav.js, frontend/src/state/State.js
* main url에 id 값을 추가했습니다 - 메인 페이지로 이동하고 싶을 때 changeUrl("/main=${id}"); 로 사용하면 됩니다.
* 게임 대기 시 취소가 가능합니다
* 2p 게임을 진행할 때 인자값 수정해서 game페이지로 이동할 수 있습니다.
* 로그아웃 버튼 클릭 시 state.js의 logout 함수를 호출하도록 수정했습니다
=> fix: main url에 id 추가

backend/transcendence/chat/consumers.py, frontend/src/components/Chat/Chat.js, frontend/src/components/Chat/ChatList.js, frontend/src/components/Chat/ChatRoom/ChatContent.js, frontend/src/pages/Chat.js, frontend/src/pages/ChatRoom.js, frontend/src/state/ChatState.js
- https://github.com/42EASY/PongPongPingPong/issues/198
- 채팅방 나가기 기능 구현
- 채팅방 진입 -> 더블 클릭으로 변경
- 서버와 클라이언트 시간 동기화 할 수 있도록 timestamp 추가
=> feat: 채팅방 나가기 기능 구현 & timestamp 추가

frontend/src/components/Main/MoreMenu.js, frontend/src/components/Main/OtherBtn.js
* 차단후 다시 차단 해제할 때 모달에 undefined가 발생하고 post가 제대로 되지 않던 부분 수정
* 차단 상태인 경우 메세지 버튼 삭제
=> fix: main의 차단 해제 undefined 해결

backend/docker_entrypoint.sh, backend/transcendence/games/fixtures/game-data.json, backend/transcendence/games/fixtures/participant-data.json, backend/transcendence/games/fixtures/tournament-data.json, backend/transcendence/games/fixtures/tournament-game-data.json
- 노말게임과 토너먼트 게임 기록 확인을 위한 dummy 데이터 추가
=> feat: 노말과 토너먼트에 대한 dummy data 추가

frontend/src/Router.js, frontend/src/components/Login/Redirect.js, frontend/src/components/Nav/InviteQueue.js, frontend/src/components/Nav/JoinQueue.js, frontend/src/pages/GameRoom.js, frontend/src/pages/Nav.js, frontend/src/state/JoinSocketManager.js, frontend/src/state/RoomSocketManager.js, frontend/src/styles/nav.css
- https://github.com/42EASY/PongPongPingPong/issues/202
* joinSocketManager, roomSocketManager 을 추가하고 인스턴스를 받아서 함수 동작하도록 수정했습니다
* gameroom에서 nav의 이벤트로 페이지 이동 시 소켓 close하도록 수정했습니다
* game페이지에 넘겨주는 인자 값 수정했습니다.
* 빠른 게임 대기 시 타이머의 두께 수정했습니다.
* 404페이지로 이동 안되던 부분 수정했습니다
=> feat: socketManager 추가

backend/transcendence/chat/consumers.py, backend/transcendence/games/game_consumer.py, backend/transcendence/games/game_queue_consumer.py, backend/transcendence/games/game_room_consumer.py, backend/transcendence/notify/consumer.py, backend/transcendence/social/block_urls.py, backend/transcendence/utils.py
- https://github.com/42EASY/PongPongPingPong/issues/206
- bot 메세지를 받아오는 기능을 구현했습니다.
- consumer에서 공통적으로 사용하는 메서드들을 utils로 분리하였습니다.
- bot 메세지 알림을 구현하였습니다.
=> feat: bot 메세지 받아오기 구현

backend/transcendence/games/game_consumer.py, backend/transcendence/games/test_game_consumer.py
- https://github.com/42EASY/PongPongPingPong/issues/213
- game에서 start_game, end_game 칼럼 저장
- press_key action에서 send 값 수정
- unpress_key action 구현
- round_start action 구현
=> feat: 게임 소켓 action 추가 구현 및 수정

backend/transcendence/games/game_consumer.py
- https://github.com/42EASY/PongPongPingPong/issues/215
- 첫 receive 메소드 실행 시 갱신된 상대 channel_name을 가져와야 하지만, 갱신 전 channel_name을 받아오는 현상이 발생하여 이를 수정
=> fix: 상대의 channel_name이 갱신이 안되는 현상 수정

backend/transcendence/games/game_consumer.py, backend/transcendence/games/test_game_consumer.py
- https://github.com/42EASY/PongPongPingPong/issues/211
- pingpong 게임 중에 값이 갱신되지 않는 현상이 발생하여 이를 수정
=> fix: pingpong 게임 중에 값이 갱신되지 않는 현상 수정

frontend/src/components/Friends/ListApi.js, frontend/src/components/Main/GameHistory.js, frontend/src/components/Main/GameResult.js, frontend/src/components/Main/GameResults.js, frontend/src/components/Main/Profile.js, frontend/src/components/Main/TournamentResult.js, frontend/src/components/Main/UserApi.js, frontend/src/components/Nav/NavApi.js, frontend/src/components/Register/SubmitButton.js, frontend/src/components/Register/TwoFactorAuth.js, frontend/src/pages/Main.js, frontend/src/state/State.js, frontend/src/styles/main.css, frontend/src/styles/nav.css
- https://github.com/42EASY/PongPongPingPong/issues/223
메인화면의 게임전적 API 연결 및 무한스크롤 적용 하였습니다.
추가로, access token 만료 시 new access token 요청 > 실패 시 logout 처리되는 부분이 무한로딩 되던 문제도 수정하였습니다.
=> feat: 게임전적 API 연결 & 무한스크롤 적용

backend/transcendence/games/game_consumer.py
- round_start action이 왔을 때 broadcast가 안되는 현상 수정
=> fix: round_start broadcast가 안되는 현상 수정

backend/transcendence/games/game_room_consumer.py
- https://github.com/42EASY/PongPongPingPong/issues/221
토너먼트 방에서 disconnect 시에 상황에 따라 broadcast
- 결승 진행 중에 disconnect 시에 게임 결과 broadcast
- 게임 시작 전 disconnect 시에 유저 정보 broadcast
=> feat: 토너먼트 방에서 disconnect 시에 처리 추가

frontend/src/components/Friends/ListApi.js, frontend/src/components/Login/Redirect.js, frontend/src/components/Main/GameResults.js, frontend/src/components/Main/UserApi.js, frontend/src/components/Nav/NavApi.js, frontend/src/components/Register/SubmitButton.js, frontend/src/components/Register/TwoFactorAuth.js, frontend/src/state/ChatSocketManager.js, frontend/src/state/GameSocketManager.js, frontend/src/state/JoinSocketManager.js, frontend/src/state/RoomSocketManager.js, frontend/src/state/State.js, frontend/src/state/WebSocketManager.js
- baseUrl을 전역변수로 관리하도록 수정하였습니다.
=> fix: baseUrl 전역변수로 관리

backend/transcendence/games/game_consumer.py, frontend/src/components/Nav/JoinQueue.js
- https://github.com/42EASY/PongPongPingPong/issues/238
- 게임 화면에서 나가기 버튼 클릭 후 다시 게임을 잡는 경우에 매칭이 되지 않는 현상이 발생하여 이를 수정
=> fix: 게임 나가기 버튼 클릭 이후 게임 매칭이 되지 않는 현상 수정

.gitignore, backend/Dockerfile, backend/docker_entrypoint.sh, backend/transcendence/run_daphne.py, backend/transcendence/security/auth_views.py, backend/transcendence/transcendence/asgi.py, backend/transcendence/transcendence/settings.py, docker-compose.yml, frontend/src/components/Login/LoginButton.js, frontend/src/state/ChatSocketManager.js, frontend/src/state/JoinSocketManager.js, frontend/src/state/State.js, frontend/src/state/WebSocketManager.js, nginx/Dockerfile, nginx/default
- https://github.com/42EASY/PongPongPingPong/issues/231
- ws -> wss
- http -> https
- 소켓 재연결 횟수 조정
=> refactor: wss, https으로 통신하도록 변경

frontend/src/components/Chat/Bot.js, frontend/src/pages/Chat.js, frontend/src/styles/sidebar.css
봇의 읽지 않은 메세지 값이 가운데 정렬되도록 css값 수정했습니다!
=> style: 읽지 않은 메세지 개수 css 수정

backend/transcendence/transcendence/settings.py
=> fix: cors 설정

frontend/src/components/Game/GameResult.js, frontend/src/pages/EndGame.js
- https://github.com/42EASY/PongPongPingPong/issues/256
- 승자와 패자의 화면에 띄울 글자를 설정할 때, 없는 결과값을 참조하고 있어 값을 변경했습니다.
=> bug: win or lose 판단 조건문 변경

backend/transcendence/games/game_board_consumer.py
- https://github.com/42EASY/PongPongPingPong/issues/258
- 진 사람의 경우 게임 루프가 계속 돌아가는 버그가 있었는데, 해당 버그를 수정하였습니다.
- handle_wall_collision 로직 분리
- self에 game_over_flag 추가하여 game_over가 중복으로 발생하지 않도록 수정
=> bug: 진 사람의 경우 루프가 안 끝나는 버그 수정

backend/transcendence/games/game_board_consumer.py
- game consumer 로직을 game board consumer로 옮기면서, 토너먼트 결과 알림 기능 또한 이동
=> refactor: 토너먼트 결과 알림 기능 game_board 컨슈머로 이동

backend/transcendence/games/game_board_consumer.py
- 기존 클라이언트단에서 처리하던 game option에 대한 로직을 추가
=> refactor: game option에 관한 처리

backend/transcendence/games/game_board_consumer.py
- https://github.com/42EASY/PongPongPingPong/issues/267
- 승패가 잘못 나오는 버그를 수정
=> bug: 게임 비정상 종료 시 승패 오류 수정

backend/transcendence/members/views.py
- https://github.com/42EASY/PongPongPingPong/issues/264
- game result가 없는 전적도 반환하는 현상 수정
=> fix: game result가 없는 game도 반환하는 현상 수정

backend/transcendence/games/game_queue_consumer.py
- https://github.com/42EASY/PongPongPingPong/issues/242
- 빠른 게임 매칭 시 자기 자신과 매칭되는 현상 방지
=> fix: 자기 자신과 게임이 매칭 되는 현상 수정

frontend/src/components/Chat/ChatRoom/BotContent.js, frontend/src/components/Main/UserApi.js, frontend/src/pages/GameRoom.js, frontend/src/pages/Nav.js, frontend/src/state/ChatSocketManager.js, frontend/src/state/JoinSocketManager.js, frontend/src/state/State.js, frontend/src/state/WebSocketManager.js
* webSocket, joinSocket, chatSocket에 interval 함수를 추가했습니다.
* 초대받은 토너먼트에 참여할 때 message로 받는 data의 변수명을 잘못 가져와서 수정했습니다.
* gameroom에서 nav를 통한 페이지 이동을 시도할 때 gameroom의 소켓을 close하도록 수정했습니다.
=> feat: socket interval

frontend/src/pages/GameRoom.js, frontend/src/state/RoomSocketManager.js
Gameroom에서 game페이지로 이동할 때 room 소켓이 제대로 disconnect 되지 않는 부분 수정했습니다
=> fix: roomsocket disconnect

frontend/src/components/Game/RemoteBoard.js
- RemoteBoard에서 사용되지 않는 값들을 삭제했습니다.
=> remove: RemoteBoard에서 사용하지 않는 코드 삭제

frontend/src/components/Chat/Chat.js, frontend/src/components/Login/Redirect.js, frontend/src/pages/BotRoom.js, frontend/src/pages/ChatRoom.js, frontend/src/state/ChatSocketManager.js, frontend/src/state/GameBoardSocketManager.js, frontend/src/state/JoinSocketManager.js, frontend/src/state/NotifySocketManager.js, frontend/src/state/RoomSocketManager.js, frontend/src/state/State.js
- https://github.com/42EASY/PongPongPingPong/issues/274
- getInstance에서 Init을 할 때의 조건문에 `WebSocket.CLOSING`을 추가하였습니다.
- WebSocketManager를 NotifySocketManager로 변경하였습니다.
- 각 메서드에서 getInstance를 하여 사용할 수 있도록 수정했습니다.
=> bug: socket이 싱글톤으로 관리되지 않는 현상

backend/transcendence/games/game_queue_consumer.py, backend/transcendence/members/views.py, backend/transcendence/security/auth_views.py, backend/transcendence/security/views.py
- https://github.com/42EASY/PongPongPingPong/issues/232
- 예외 처리를 추가하였습니다.
=> fix: 빠진 예외처리 추가

backend/transcendence/transcendence/settings.py
- https://github.com/42EASY/PongPongPingPong/issues/279
- 짧은 시간에 채팅을 많이 보내는 경우 소켓이 닫히는 현상 발생 
- Channel_layer의 설정을 바꾸어 최대로 들고 있는 메세지 수를 증가
=> fix: channel_layer 설정 변경

backend/transcendence/games/game_board_consumer.py
- https://github.com/42EASY/PongPongPingPong/issues/277
- 원활한 게임을 위해 paddle_speed 및 ball_speed를 조정하였습니다.
- already_game_over 메서드의 조건문을 수정하였습니다.
- 한 명이 중간에 게임을 나가는 경우, 게임 점수를 업데이트하도록 수정하였습니다.
=> fix: game board consumer 수정

frontend/src/pages/GameRoom.js, frontend/src/styles/gameroom.css
gameroom - final 인 경우 처리를 추가했습니다
* 위치 center로 오도록 수정
* border 값 수정
=> style: gameroom 결승인 경우 css 수정

backend/transcendence/games/game_board_consumer.py
=> fix: 토너먼트 경기 종료 후 알림 오류 수정

Makefile, backend/docker_entrypoint.sh, docker-compose.yml
- docker-compose.yml 볼륨 설정을 수정
- 개발용 코드 주석처리
=> fix: docker-compose 및 makefile 설정 변경

frontend/src/components/Main/GameResults.js, frontend/src/components/Register/TwoFactorAuth.js
전적 호출 api, 2차 인증 otp api 토큰 만료 시 재귀되는 부분에서 인자가 누락된 부분 수정하였습니다.
=> bug: api 재귀 인자 누락된 부분 수정

frontend/index.html, frontend/src/pages/Register.js
css 가 로딩된 이후 요소들이 화면에 보이게 하도록 display none 에서 block 으로 변경하게 적용해두었으나,
register 페이지에서는 변경되지 않는 문제가 있어 임시 조치 하였습니다.
=> bug: display none>block 변경되지 않는 문제 임시 조치

frontend/src/components/Modal/GameResultTable.js
게임결과 모달에서 ranking을 찾아서 값을 넣도록 수정했습니다
=> fix: 게임결과 ranking을 확인하고 값을 넣도록 수정

backend/transcendence/games/game_room_consumer.py
- 토너먼트 결승 중 disconnect 안되는 현상 수정
=> fix: 토너먼트 결승 중 disconnect 안되는 현상 수정

frontend/src/Router.js, frontend/src/components/Chat/Profile/InfoBtn.js, frontend/src/components/Friends/Blocked.js, frontend/src/components/Friends/ListApi.js, frontend/src/components/Game/Board.js, frontend/src/components/Game/Info.js, frontend/src/components/Game/RemoteBoard.js, frontend/src/components/Login/Redirect.js, frontend/src/components/Main/UserApi.js, frontend/src/components/Modal/Modal.js, frontend/src/components/Modal/addContent.js, frontend/src/components/Nav/NavApi.js, frontend/src/components/Register/TwoFactorAuth.js, frontend/src/pages/BotRoom.js, frontend/src/pages/Chat.js, frontend/src/pages/ChatRoom.js, frontend/src/pages/EndGame.js, frontend/src/pages/Friends.js, frontend/src/pages/Game.js, frontend/src/pages/GameRoom.js, frontend/src/pages/Login.js, frontend/src/pages/Main.js, frontend/src/pages/NotFound.js, frontend/src/pages/Profile.js, frontend/src/pages/Register.js, frontend/src/state/State.js, frontend/src/styles/modal.css
* console.log 모두 삭제했습니다
* display:none 부분 원래대로 복구했습니다
* 2p 최대스코어 수정했습니다
* 모달 텍스트 정렬했습니다
=> bug: 프론트 정리
