42EASY/PongPongPingPong

backend/transcendence/games/game_consumer.py
backend/transcendence/games/game_queue_consumer.py
backend/transcendence/games/game_room_consumer.py
backend/transcendence/games/test_game_consumer.py
backend/transcendence/games/test_game_queue_consumer.py
backend/transcendence/games/test_game_room_consumer.py

- https://github.com/42EASY/PongPongPingPong/issues/128
- 현재 user_id를 action을 보낼 때 마다 같이 보내도록 했는데, 이를 connect 시에 user 정보를 받아와서 더 이상 action에서 user_id를 받아오지 않도록 수정
- token의 유효성을 검사하는 middleware에서 저장하는 user 정보를 받아와서 저장
- 하지만 테스트코드 상에서는 middleware를 타지 않아, 임의로 user 정보를 넣어줌
- 사용하지 않는 user_id와 json data 값들은 다음 pr에서 수정할 예정

fix: websocket connect 시에 user 값 받아오도록 수정

---

frontend/src/components/Friends/Friend.js
frontend/src/components/Friends/Options.js
frontend/src/components/GameRoom/WaitingPlayer.js
frontend/src/components/Main/MoreMenu.js
frontend/src/components/Nav/FastGameStart.js
frontend/src/components/Nav/InviteQueue.js
frontend/src/components/Nav/JoinQueue.js
frontend/src/pages/Friends.js
frontend/src/pages/GameRoom.js

- https://github.com/42EASY/PongPongPingPong/issues/158
게임 시작하기 전 join_queue 소켓 추가했습니다!
game페이지로 이동할 때 `changeUrl("/game", data);` 의 data 모음
* 2P game
`data = { option: "2P", mode: ["CLASSIC" | "SPEED"] };`
* normal game
`data = { option: "NORMAL", mode : ["CLASSIC" | "SPEED"], game_id: "1", `
`player_info: [{ user_id, nickname, image_url }, { user_id, nickname, image_url }] };`
* tournament game
`data = { mode: ["SEMI_FINAL" | "FINAL" ], game_id: "1", player_info: {} };`
* 준결승 시합 끝나고 gameroom 이동시 아래처럼 넣어주세요!
`changeUrl("/gameroom", {mode: "FINAL", room_id: id});`
friends의 친구 목록에서 스크롤 한 후 차단목록으로 이동하면 
친구목록의 리스트와 차단목록의 리스트가 겹쳐지는 오류가 있었는데 수정했습니다

feat: join_queue 소켓 추가

---

backend/transcendence/games/game_queue_consumer.py
backend/transcendence/games/test_game_queue_consumer.py

- https://github.com/42EASY/PongPongPingPong/issues/171
normal, tournament 빠른 시작시에 오류 발생
- registered_user에 지워진 데이터가 남아있어서, 이를 참조하는 과정에서 db 오류 발생하는 부분 해결
- normal 인 경우 registered_user에 2명이 들어가야하는데, 3명이 들어가는 오류 발생하는 부분 해결
테스트코드 실행 후에 더미 데이터가 계속 남아있는 현상 발생하여, 이를 수정

fix: 게임 빠른 시작 시에 오류 발생 해결

---

backend/transcendence/games/game_consumer.py
backend/transcendence/games/game_queue_consumer.py
backend/transcendence/games/game_room_consumer.py
backend/transcendence/games/test_game_consumer.py
backend/transcendence/games/test_game_queue_consumer.py
backend/transcendence/games/test_game_room_consumer.py

- https://github.com/42EASY/PongPongPingPong/issues/156
- 게임 큐, 게임 방, 게임에 대한 disconnect 구현
- 토너먼트 진행 중에 disconnect가 발생하면 해당 유저는 게임을 패배하는 로직 구현
- 게임 큐 소켓에서, 게임 방 소켓으로 넘어갈 때 게임 큐 소켓을 disconnect하면 유저 정보가 다 지워지는 버그가 발생한 것 확인. 추후 수정 예정

feat: 게임 관련 disconnect 구현

---

backend/transcendence/chat/consumers.py
backend/transcendence/notify/consumer.py

- https://github.com/42EASY/PongPongPingPong/issues/164
- chat과 notify 소켓을 분리
- 차단 유저 관련 기능 구현 => 1. 차단한 유저에게 메세지 받지 않음 2. 차단한 유저 채팅 리스트에서 보여주지 않음 3. 차단한 유저에게 메세지 보내기 막음
- 오프라인 유저 관련 기능 구현 => 1. 오프라인 유저에게 메세지 보내기 막음
- 채팅 상대방 현재 상태(online, isblocked)를 가져오는 기능 추가
- 채팅 상대방에게 현재 상태 알려주는 기능 추가

fix: chat & notify 수정 및 차단 & 오프라인 유저 관련 기능 구현

---

backend/transcendence/security/auth_views.py
frontend/src/state/State.js

- https://github.com/42EASY/PongPongPingPong/issues/200
- refresh token이 redis에 제대로 저장되지 않는 문제를 해결했습니다.
- 프론트엔드에서 쿠키를 포함시켜 logout 요청을 보내도록 설정해줬습니다.

fix: refresh token 관련 버그 픽스

---

frontend/index.html
frontend/src/components/Chat/Chat.js
frontend/src/components/Chat/ChatRoom/BotContent.js
frontend/src/pages/BotRoom.js
frontend/src/pages/Chat.js
frontend/src/pages/ChatRoom.js
frontend/src/state/WebSocketManager.js
frontend/src/styles/toast.css

- https://github.com/42EASY/PongPongPingPong/issues/208
- 토스트(알림)을 사이드바보다 상단에 위치하도록 변경했습니다.
- 타임스탬프 포맷을 변경했습니다.
- 봇 알림이 오면 "새로운 알림이 있습니다"라는 토스트가 뜨도록 기능을 구현했습니다.
- 봇 채팅방 입장 시 현재까지의 알림을 받아오는 기능을 구현했습니다.
- 채팅 목록에 있을 때 실시간으로 메세지 카운트를 바꿀 수 있도록 했습니다.

fix: 토스트 순서 변경 및 채팅 기능 향상

---

backend/transcendence/games/distributed_lock.py
backend/transcendence/games/game_room_consumer.py
backend/transcendence/games/test_game_room_consumer.py
backend/transcendence/social/friends_views.py

- https://github.com/42EASY/PongPongPingPong/issues/193
- 게임 방에서 초대 시에 반환하는 tournament_id 대신 room_id로 변경
- distributed lock에서 redis host를 localhost로 한 부분 변경
- friend_view에서 block_list를 friend_list로 변경
- 토너먼트 게임 시작 시 status 메세지 변경

FIX: 토너먼트 id 반환 부분 수정 및 redis host 변경 등 세부 사항 변경

---

frontend/src/components/Chat/ChatRoom/BotContent.js
frontend/src/components/Friends/Options.js
frontend/src/components/GameRoom/PercentBar.js
frontend/src/components/Modal/ModalsInfo.js
frontend/src/components/Nav/JoinQueue.js
frontend/src/pages/Friends.js
frontend/src/pages/GameRoom.js
frontend/src/pages/Nav.js
frontend/src/state/JoinSocketManager.js

* 토너먼트 게임 join 시 초대하는 경우 메세지의 status : "game create success" 처리를 추가했습니다
* Friends에서 게임 초대 시 넘기는 인자값이 임시값에서 user의 id와 status를 받을 수 있도록 수정, 
친구 목록 받아올 때 dataSize 크기를 더 많이 받아오도록 수정했습니다
* JoinSocketManager의 재연결 시도 카운트값 초기화, 게임 join이 되면 close()하도록 변경, 
nav에서 다시 connect 시도할 수 있도록 수정했습니다
* 토너먼트 방에 4명 모두 모이게 되면 gameStartSoon 모달 적용했습니다
* 토너먼트 게임 초대 입장 시 이미 게임방에 인원이 4명인 경우 enterFail_fullRoom 모달 적용 적용했습니다
(modalInfo에서 enterFaill_fullRoom으로 오타가 있어서 수정했고 실제로 테스트는 못했습니다)
* 승률이 100%인 경우 0% 글씨가 보이지 않도록 수정했습니다

fix: socket 관련 코드 수정

---

backend/transcendence/members/views.py

- 토너먼트 전적 반환시에 원하는 size대로 반환이 되지 않는 현상 발생하여 이를 수정

fix: 토너먼트 전적을 받아올 때 원하는 size 대로 반환하지 않는 현상 수정

---

backend/transcendence/games/game_consumer.py
backend/transcendence/games/game_queue_consumer.py
backend/transcendence/games/game_room_consumer.py

- https://github.com/42EASY/PongPongPingPong/issues/229
- 전적 검색시 게임의 start_time, end_time이 제대로 저장되지 않아서 400에러 발생하였고, 이를 수정

fix: 게임의 start, end time이 잘 저장 안되는 현상 수정

---

frontend/src/components/Chat/ChatRoom/BotContent.js
frontend/src/components/Modal/Modal.js
frontend/src/components/Modal/ModalsInfo.js
frontend/src/pages/ChatRoom.js
frontend/src/pages/GameRoom.js
frontend/src/pages/Nav.js
frontend/src/state/JoinSocketManager.js
frontend/src/state/RoomSocketManager.js

Modal
* 모달 뒤 화면 스크롤 되지 않도록 했습니다
* chatFail_offline -> chatFail_offlineUser 로 모달명 수정했습니다
* chatFail_offlineUser 호출 시 계속해서 input에 메세지 입력이 가능하던 부분 수정했습니다
Sidebar
* Chat, Friends의 목록에 스크롤이 없는 경우 사이드바 외부의 화면이 스크롤 되던 부분 수정했습니다
* 수정하면서 chat.js에 프리티어가 적용되어 포맷이 일부 변경되었습니다
* 게임초대 메세지 노말과 토너먼트 부분이 잘못 연결되어 있어서 수정했습니다
GameRoom
* 토너먼트 게임 대기 방에서 결승 대기 중인 상황에 상대방의 연결이 끊기게 되면 메인 페이지로 이동하도록 했습니다
* 소켓에 close 함수를 추가하고 게임방에서 페이지 이동이 발생할 때 추가한 함수를 사용하도록 수정했습니다
* joinsocketmanager와 roomsocketmanager에 에러 발생 시 명시적으로 소켓을 close 하도록 수정했습니다

fix: scroll , joingame과 gameroom 소켓 수정

---

frontend/src/components/Modal/Modal.js
frontend/src/pages/Main.js

* 빠른 게임시작 같은 모달창을 닫는 이벤트없이 페이지 이동하게 되면 스크롤이 없어지는 문제 해결했습니다

fix: 빠른 게임 후 스크롤 동작하도록 수정

---

backend/transcendence/games/game_board_consumer.py
backend/transcendence/transcendence/routing.py
frontend/src/components/Game/RemoteBoard.js
frontend/src/components/Modal/ModalsInfo.js
frontend/src/pages/Game.js
frontend/src/state/GameBoardSocketManager.js
frontend/src/state/State.js

- https://github.com/42EASY/PongPongPingPong/issues/245
- 서버에서 게임에 관련한 로직 계산할 수 있도록 Consumer 추가
- 클라이언트는 정보 받아서 그려줄 수 있도록 수정
- 토너먼트 끝나고 알림 보내는 기능 이사(?)
- 현재 2인 게임에만 적용되어 있어 토너먼트에도 적용해야함
- 스피드 / 클래식 따로 구현되어있지 않음

refactor: 서버에서 계산하도록 게임 로직 수정

---

backend/transcendence/games/game_queue_consumer.py

- https://github.com/42EASY/PongPongPingPong/issues/247
- 매칭 진행 중 의도치 않은 매칭 종료 후 게임 전적 페이지 400 뜨는 현상 발생
- participant 테이블에 opponent_id가 null 값이 들어가 있어 해당 현상이 발생한 것이라고 판단
- 기존 participant는 game이 만들어질 때 opponent_id 값을 비워둔 채로 생성 후, 게임 상대가 정해지면 그때 update 하도록 처리해놓았는데, 이를 게임 상대가 정해질 때 participant가 한번에 만들어질 수 있도록 수정

fix: 매칭 진행 중 의도치 않은 매칭 종료 후 게임 전적 페이지 400 뜨는 현상 수정

---

backend/transcendence/games/game_board_consumer.py

- https://github.com/42EASY/PongPongPingPong/issues/250
- 게임 game_over 시에 현재 user_id, score만 반환하도록 되어있는데, result도 추가로 반환하도록 수정

fix: game over시에 result도 전송하도록 추가

---

backend/transcendence/members/views.py

- https://github.com/42EASY/PongPongPingPong/issues/252
- 게임 전적을 start_time을 기준으로 내림차순으로 정렬하도록 수정

fix: 게임 전적을 start time 기준으로 내림차순 정렬

---

frontend/src/components/Game/RemoteBoard.js
frontend/src/pages/Game.js

* game에서 받는 data 값이 NORMAL 모드인 경우와 TOURNAMENT 모드인 경우 값이 달라서
게임 상단에 표시되는 유저 정보 값이 제대로 표시되지 않는 부분 수정했습니다.

fix: tournament, noraml로 나누어 player_info 처리

---

backend/Dockerfile
backend/docker_entrypoint.sh
backend/transcendence/run_daphne.py
docker-compose.yml
nginx/Dockerfile
nginx/default

- https://github.com/42EASY/PongPongPingPong/issues/262
- 개발 및 평가 시 편의를 위해 각각의 인증서를 발급받아 ssl 통신이 가능하도록 변경
- 배포 시에는 다른 방식으로 인증서를 받도록 수정

fix: 서버와 nginx 인증서 분리

---

frontend/src/App.js
frontend/src/Router.js
frontend/src/components/Register/Nickname.js
frontend/src/components/Register/SubmitButton.js
frontend/src/components/Register/TwoFactorAuth.js
frontend/src/pages/BotRoom.js
frontend/src/pages/Chat.js
frontend/src/pages/ChatRoom.js
frontend/src/pages/EndGame.js
frontend/src/pages/Friends.js
frontend/src/pages/Game.js
frontend/src/pages/GameRoom.js
frontend/src/pages/Login.js
frontend/src/pages/Main.js
frontend/src/pages/NotFound.js
frontend/src/pages/Profile.js
frontend/src/pages/Register.js

- register 페이지의 중복 닉네임 API 응답이 명세와 달라 에러 발생된 부분 수정
- register 페이지의 2차인증 활성화 클릭 후 비정상 종료 시 다시 비활성화로 돌아가지 않던 부분 수정
- 로그인 없이/인자 없이 url로 페이지 이동하는 경우 로그인 페이지/메인 페이지로 이동되도록 적용
- 모든 페이지에서 css 적용 전까지 display: none 처리 적용 하였습니다.

fix: register 페이지 버그 수정 및 로그인 없이 url로 페이지 이동 제한 적용

---

backend/transcendence/games/game_room_consumer.py

- https://github.com/42EASY/PongPongPingPong/issues/283
- 토너먼트 결승 게임이 안되는 현상 발생
- 준결승 후 disconnect 시에 토너먼트의 게임 registered가 삭제되어, 결승 게임이 안되는 현상이 발생하였고 이를 수정함

fix: 토너먼트 결승 게임을 위한 게임방에 입장이 안되는 현상 수정
